/**
 * Deterministic Alerting Seed Data & In-Memory Store
 *
 * Provides realistic, deterministic alerts, rules, and event logs for OpsConsole.
 * Scoped strictly by workspaceId and environmentId.
 * Labeled clearly as "Simulated SRE Telemetry Model".
 */

import type { Alert, AlertEvent, AlertRule } from "./types";

export const DEFAULT_WORKSPACE_ID = "ws_demo_001";
export const DEFAULT_ENVIRONMENT_ID = "env_prod_001";

// ─── Initial Seed Rules ───────────────────────────────────────────────────────

export const SEEDED_ALERT_RULES: AlertRule[] = [
  {
    id: "rule_notif_burn_001",
    name: "Notification Worker Fast Burn Rate",
    description: "Triggers when the burn rate multiplier exceeds 5.0x, depleting the error budget rapidly.",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    serviceId: "svc_notif_005",
    condition: {
      metricType: "BURN_RATE",
      operator: "GT",
      threshold: 5.0,
      windowMinutes: 60,
      unit: "x",
    },
    severity: "CRITICAL",
    isEnabled: true,
    cooldownMinutes: 15,
    labels: { tier: "3", team: "infra-async", runbook: "rbk-queue-drain" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule_orders_latency_002",
    name: "Orders API P95 Latency Elevated",
    description: "Triggers when P95 latency exceeds 250ms over a 5-minute sliding evaluation window.",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    serviceId: "svc_orders_002",
    condition: {
      metricType: "LATENCY_P95",
      operator: "GT",
      threshold: 250,
      windowMinutes: 5,
      unit: "ms",
    },
    severity: "WARNING",
    isEnabled: true,
    cooldownMinutes: 10,
    labels: { tier: "1", team: "checkout-core" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule_payments_budget_003",
    name: "Payments API Error Budget Erosion",
    description: "Triggers when remaining error budget falls below 30% under sustained degradation.",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    serviceId: "svc_payments_001",
    condition: {
      metricType: "ERROR_BUDGET_REMAINING",
      operator: "LT",
      threshold: 30.0,
      windowMinutes: 60,
      unit: "%",
    },
    severity: "WARNING",
    isEnabled: true,
    cooldownMinutes: 30,
    labels: { tier: "1", team: "fintech-core", critical: "true" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule_auth_error_rate_004",
    name: "Auth API Error Rate Spike",
    description: "Triggers when HTTP 5xx error rate exceeds 1.0% on authentication flows.",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    serviceId: "svc_auth_003",
    condition: {
      metricType: "ERROR_RATE",
      operator: "GT",
      threshold: 1.0,
      windowMinutes: 5,
      unit: "%",
    },
    severity: "CRITICAL",
    isEnabled: true,
    cooldownMinutes: 10,
    labels: { tier: "1", team: "sec-auth" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule_user_mem_005",
    name: "User Profile Memory Saturation",
    description: "Triggers when container memory saturation exceeds 80%.",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    serviceId: "svc_user_004",
    condition: {
      metricType: "SATURATION_MEMORY",
      operator: "GT",
      threshold: 80.0,
      windowMinutes: 15,
      unit: "%",
    },
    severity: "WARNING",
    isEnabled: true,
    cooldownMinutes: 15,
    labels: { tier: "2", team: "user-team" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

// ─── Initial Seed Alerts ──────────────────────────────────────────────────────

export const SEEDED_ALERTS: Alert[] = [
  {
    id: "alt_notif_burn_001",
    ruleId: "rule_notif_burn_001",
    ruleName: "Notification Worker Fast Burn Rate",
    serviceId: "svc_notif_005",
    serviceName: "Notification Worker",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    severity: "CRITICAL",
    status: "FIRING",
    conditionSnapshot: {
      metricType: "BURN_RATE",
      operator: "GT",
      threshold: 5.0,
      observedValue: 12.5,
      unit: "x",
    },
    fingerprint: `${DEFAULT_WORKSPACE_ID}:${DEFAULT_ENVIRONMENT_ID}:svc_notif_005:rule_notif_burn_001`,
    title: "Notification Worker Fast Burn Rate — Notification Worker",
    summary: "Observed BURN_RATE of 12.5x (Threshold: GT 5.0x). Error budget estimated exhaustion in ~57 hours.",
    triggeredAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "alt_orders_lat_002",
    ruleId: "rule_orders_latency_002",
    ruleName: "Orders API P95 Latency Elevated",
    serviceId: "svc_orders_002",
    serviceName: "Orders API",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    severity: "WARNING",
    status: "ACKNOWLEDGED",
    conditionSnapshot: {
      metricType: "LATENCY_P95",
      operator: "GT",
      threshold: 250,
      observedValue: 340,
      unit: "ms",
    },
    fingerprint: `${DEFAULT_WORKSPACE_ID}:${DEFAULT_ENVIRONMENT_ID}:svc_orders_002:rule_orders_latency_002`,
    title: "Orders API P95 Latency Elevated — Orders API",
    summary: "Observed LATENCY_P95 of 340ms (Threshold: GT 250ms). Downstream dependency svc_payments_001 is degraded.",
    triggeredAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    lastEvaluatedAt: new Date().toISOString(),
    acknowledgedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    acknowledgedBy: "Priya Nair",
  },
  {
    id: "alt_pay_budget_003",
    ruleId: "rule_payments_budget_003",
    ruleName: "Payments API Error Budget Erosion",
    serviceId: "svc_payments_001",
    serviceName: "Payments API",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    severity: "WARNING",
    status: "FIRING",
    conditionSnapshot: {
      metricType: "ERROR_BUDGET_REMAINING",
      operator: "LT",
      threshold: 30.0,
      observedValue: 18.5,
      unit: "%",
    },
    fingerprint: `${DEFAULT_WORKSPACE_ID}:${DEFAULT_ENVIRONMENT_ID}:svc_payments_001:rule_payments_budget_003`,
    title: "Payments API Error Budget Erosion — Payments API",
    summary: "Observed ERROR_BUDGET_REMAINING of 18.5% (Threshold: LT 30.0%). 30-day budget burning at 3.2x rate.",
    triggeredAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "alt_user_mem_004",
    ruleId: "rule_user_mem_005",
    ruleName: "User Profile Memory Saturation",
    serviceId: "svc_user_004",
    serviceName: "User Profile API",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    severity: "WARNING",
    status: "RESOLVED",
    conditionSnapshot: {
      metricType: "SATURATION_MEMORY",
      operator: "GT",
      threshold: 80.0,
      observedValue: 62.0,
      unit: "%",
    },
    fingerprint: `${DEFAULT_WORKSPACE_ID}:${DEFAULT_ENVIRONMENT_ID}:svc_user_004:rule_user_mem_005`,
    title: "User Profile Memory Saturation — User Profile API",
    summary: "Observed SATURATION_MEMORY of 62.0% (Threshold: GT 80.0%). Memory stabilized after garbage collection.",
    triggeredAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    lastEvaluatedAt: new Date().toISOString(),
    resolvedAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    resolvedBy: "system:evaluator",
    resolutionNote: "Telemetry condition cleared (Observed: 62.0%)",
  },
];

// ─── Initial Seed Events ──────────────────────────────────────────────────────

export const SEEDED_ALERT_EVENTS: AlertEvent[] = [
  {
    id: "evt_notif_001",
    alertId: "alt_notif_burn_001",
    eventType: "TRIGGERED",
    previousStatus: "NORMAL",
    newStatus: "FIRING",
    actor: "system:evaluator",
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    note: "Condition breach: Observed BURN_RATE of 12.5x exceeds threshold 5.0x.",
  },
  {
    id: "evt_orders_001",
    alertId: "alt_orders_lat_002",
    eventType: "TRIGGERED",
    previousStatus: "NORMAL",
    newStatus: "FIRING",
    actor: "system:evaluator",
    timestamp: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    note: "Condition breach: Observed LATENCY_P95 of 340ms exceeds threshold 250ms.",
  },
  {
    id: "evt_orders_002",
    alertId: "alt_orders_lat_002",
    eventType: "ACKNOWLEDGED",
    previousStatus: "FIRING",
    newStatus: "ACKNOWLEDGED",
    actor: "usr_priya_003",
    timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    note: "Acknowledged by Priya Nair. Investigating downstream payments latency impact.",
  },
  {
    id: "evt_pay_001",
    alertId: "alt_pay_budget_003",
    eventType: "TRIGGERED",
    previousStatus: "NORMAL",
    newStatus: "FIRING",
    actor: "system:evaluator",
    timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    note: "Condition breach: Observed ERROR_BUDGET_REMAINING of 18.5% is below threshold 30.0%.",
  },
  {
    id: "evt_user_001",
    alertId: "alt_user_mem_004",
    eventType: "TRIGGERED",
    previousStatus: "NORMAL",
    newStatus: "FIRING",
    actor: "system:evaluator",
    timestamp: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    note: "Condition breach: Observed SATURATION_MEMORY of 84.0% exceeds threshold 80.0%.",
  },
  {
    id: "evt_user_002",
    alertId: "alt_user_mem_004",
    eventType: "RESOLVED",
    previousStatus: "FIRING",
    newStatus: "RESOLVED",
    actor: "system:evaluator",
    timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    note: "Telemetry condition cleared. Observed SATURATION_MEMORY dropped to 62.0%.",
  },
];
