/**
 * Seeded Demo Data for Notification Domain
 *
 * Local-first, deterministic, fully isolated by workspaceId and environmentId.
 */

import type {
  Notification,
  NotificationChannel,
  NotificationPreference,
  NotificationRule,
} from "./types";

export const DEFAULT_WORKSPACE_ID = "ws-demo";
export const DEFAULT_ENVIRONMENT_ID = "env-prod";

// ─── Seeded Notification Channels ─────────────────────────────────────────────

export const SEEDED_CHANNELS: NotificationChannel[] = [
  {
    id: "chan-inapp",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "IN_APP",
    name: "Console Live Activity Feed",
    description: "In-app operational alerts and activity popups inside OpsConsole",
    destination: "OpsConsole Live Activity Feed",
    isEnabled: true,
    isSimulated: true,
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "chan-slack-sre",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "SLACK",
    name: "Slack #sre-critical",
    description: "Primary incident response channel for high-priority production outages",
    destination: "#sre-critical",
    isEnabled: true,
    isSimulated: true,
    config: { channelId: "C0198SRECRIT" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "chan-slack-ops",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "SLACK",
    name: "Slack #ops-alerts",
    description: "General alerts and notification broadcast channel",
    destination: "#ops-alerts",
    isEnabled: true,
    isSimulated: true,
    config: { channelId: "C0298OPSALERT" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "chan-webhook-pager",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "WEBHOOK",
    name: "On-Call Pager Gateway",
    description: "Automated webhook relay for secondary on-call escalation",
    destination: "https://api.internal/webhooks/ops-pager",
    isEnabled: true,
    isSimulated: true,
    config: { format: "json", timeoutMs: "3000" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "chan-email-sre",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "EMAIL",
    name: "SRE Escalation Mailbox",
    description: "Distribution list for SRE team on-call engineers",
    destination: "sre-team@opsconsole.internal",
    isEnabled: true,
    isSimulated: true,
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "chan-teams-ops",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    type: "TEAMS",
    name: "Teams Engineering Operations",
    description: "Broadcasts incident updates to engineering org Teams channel",
    destination: "Engineering Operations Hub",
    isEnabled: true,
    isSimulated: true,
    config: { webhookUrl: "https://outlook.office.internal/webhook/eng-ops" },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

// ─── Seeded Notification Rules ────────────────────────────────────────────────

export const SEEDED_RULES: NotificationRule[] = [
  {
    id: "rule-sev1-critical",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    name: "SEV1 Critical Outage Immediate Escalation",
    description: "Routes SEV1 alerts and incidents across In-App, Slack #sre-critical, and Pager webhook with 5-minute cooldown",
    isEnabled: true,
    priority: 1,
    eventTypes: ["ALERT_FIRING", "INCIDENT_CREATED"],
    severities: ["SEV1"],
    serviceIds: ["*"],
    destinations: [
      { channelType: "IN_APP", destination: "OpsConsole Live Activity Feed", targetName: "In-App Feed", enabled: true },
      { channelType: "SLACK", destination: "#sre-critical", targetName: "Slack Critical Room", enabled: true },
      { channelType: "WEBHOOK", destination: "https://api.internal/webhooks/ops-pager", targetName: "Pager Webhook", enabled: true },
    ],
    cooldownMinutes: 5,
    lastTriggeredAt: "2026-03-02T10:15:00.000Z",
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule-sev2-high",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    name: "SEV2 High Severity Routing",
    description: "Dispatches SEV2 notifications to In-App, Email, and Slack #ops-alerts with 10-minute cooldown",
    isEnabled: true,
    priority: 2,
    eventTypes: ["ALERT_FIRING", "ALERT_ACKNOWLEDGED", "INCIDENT_CREATED", "INCIDENT_ACKNOWLEDGED"],
    severities: ["SEV2"],
    serviceIds: ["*"],
    destinations: [
      { channelType: "IN_APP", destination: "OpsConsole Live Activity Feed", targetName: "In-App Feed", enabled: true },
      { channelType: "EMAIL", destination: "sre-team@opsconsole.internal", targetName: "SRE Email", enabled: true },
      { channelType: "SLACK", destination: "#ops-alerts", targetName: "Slack Ops Room", enabled: true },
    ],
    cooldownMinutes: 10,
    lastTriggeredAt: "2026-03-02T09:30:00.000Z",
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule-sev3-warning",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    name: "SEV3 / Moderate Warning Routing",
    description: "In-App console notifications for SEV3 warnings and transient degradation",
    isEnabled: true,
    priority: 3,
    eventTypes: ["ALERT_FIRING", "ALERT_RESOLVED"],
    severities: ["SEV3"],
    serviceIds: ["*"],
    destinations: [
      { channelType: "IN_APP", destination: "OpsConsole Live Activity Feed", targetName: "In-App Feed", enabled: true },
    ],
    cooldownMinutes: 15,
    lastTriggeredAt: "2026-03-02T08:00:00.000Z",
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "rule-incident-lifecycle",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    name: "Incident Lifecycle Broadcast",
    description: "Notifies team channels on incident mitigation, updates, and resolution",
    isEnabled: true,
    priority: 1,
    eventTypes: ["INCIDENT_MITIGATED", "INCIDENT_RESOLVED"],
    severities: ["SEV1", "SEV2", "SEV3", "SEV4"],
    serviceIds: ["*"],
    destinations: [
      { channelType: "IN_APP", destination: "OpsConsole Live Activity Feed", targetName: "In-App Feed", enabled: true },
      { channelType: "SLACK", destination: "#sre-critical", targetName: "Slack Incident Channel", enabled: true },
      { channelType: "TEAMS", destination: "Engineering Operations Hub", targetName: "Teams Channel", enabled: true },
    ],
    cooldownMinutes: 2,
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

// ─── Seeded Notifications ─────────────────────────────────────────────────────

export const SEEDED_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-001",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    source: "ALERT",
    sourceId: "alert-001",
    serviceId: "srv-notif-worker",
    serviceName: "Notification Worker",
    severity: "SEV1",
    eventType: "ALERT_FIRING",
    title: "High Error Rate (> 2.0%) on Notification Worker",
    message: "Notification Worker observed 4.2% error rate in ap-south-1. Error budget burn rate is 14.2x.",
    status: "DELIVERED",
    fingerprint: "ws-demo:env-prod:ALERT:alert-001:ALERT_FIRING",
    ruleId: "rule-sev1-critical",
    ruleName: "SEV1 Critical Outage Immediate Escalation",
    relatedAlertId: "alert-001",
    isSimulated: true,
    createdAt: "2026-03-02T10:15:00.000Z",
    updatedAt: "2026-03-02T10:15:02.000Z",
    deliveries: [
      {
        id: "del-001-1",
        notificationId: "notif-001",
        channelType: "IN_APP",
        destination: "OpsConsole Live Activity Feed",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T10:15:00.500Z",
        createdAt: "2026-03-02T10:15:00.000Z",
        updatedAt: "2026-03-02T10:15:00.500Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T10:15:00.500Z",
            adapter: "InAppNotificationAdapter",
            channelType: "IN_APP",
            destination: "OpsConsole Live Activity Feed",
            metadata: { simulated: true, mode: "LOCAL_SIMULATED", deliveredToUiFeed: true },
          },
        ],
      },
      {
        id: "del-001-2",
        notificationId: "notif-001",
        channelType: "SLACK",
        destination: "#sre-critical",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T10:15:01.200Z",
        createdAt: "2026-03-02T10:15:00.000Z",
        updatedAt: "2026-03-02T10:15:01.200Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T10:15:01.200Z",
            adapter: "SlackNotificationAdapter",
            channelType: "SLACK",
            destination: "#sre-critical",
            metadata: { simulated: true, mode: "LOCAL_SIMULATED", messageTs: "1740910501.000100" },
          },
        ],
      },
      {
        id: "del-001-3",
        notificationId: "notif-001",
        channelType: "WEBHOOK",
        destination: "https://api.internal/webhooks/ops-pager",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T10:15:02.000Z",
        createdAt: "2026-03-02T10:15:00.000Z",
        updatedAt: "2026-03-02T10:15:02.000Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T10:15:02.000Z",
            adapter: "WebhookNotificationAdapter",
            channelType: "WEBHOOK",
            destination: "https://api.internal/webhooks/ops-pager",
            metadata: { simulated: true, httpStatus: 200, headers: { "X-OpsConsole-Delivery": "simulated" } },
          },
        ],
      },
    ],
  },
  {
    id: "notif-002",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    source: "ALERT",
    sourceId: "alert-002",
    serviceId: "srv-orders-api",
    serviceName: "Orders API",
    severity: "SEV2",
    eventType: "ALERT_FIRING",
    title: "Elevated p95 Latency (> 250ms) on Orders API",
    message: "Orders API observed p95 latency spike to 410ms. Burn rate is 3.5x.",
    status: "DELIVERED",
    fingerprint: "ws-demo:env-prod:ALERT:alert-002:ALERT_FIRING",
    ruleId: "rule-sev2-high",
    ruleName: "SEV2 High Severity Routing",
    relatedAlertId: "alert-002",
    isSimulated: true,
    createdAt: "2026-03-02T09:30:00.000Z",
    updatedAt: "2026-03-02T09:30:01.500Z",
    deliveries: [
      {
        id: "del-002-1",
        notificationId: "notif-002",
        channelType: "IN_APP",
        destination: "OpsConsole Live Activity Feed",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T09:30:00.300Z",
        createdAt: "2026-03-02T09:30:00.000Z",
        updatedAt: "2026-03-02T09:30:00.300Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T09:30:00.300Z",
            adapter: "InAppNotificationAdapter",
            channelType: "IN_APP",
            destination: "OpsConsole Live Activity Feed",
            metadata: { simulated: true, mode: "LOCAL_SIMULATED" },
          },
        ],
      },
      {
        id: "del-002-2",
        notificationId: "notif-002",
        channelType: "EMAIL",
        destination: "sre-team@opsconsole.internal",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T09:30:01.000Z",
        createdAt: "2026-03-02T09:30:00.000Z",
        updatedAt: "2026-03-02T09:30:01.000Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T09:30:01.000Z",
            adapter: "EmailNotificationAdapter",
            channelType: "EMAIL",
            destination: "sre-team@opsconsole.internal",
            metadata: { simulated: true, mode: "LOCAL_SIMULATED", messageId: "<sim-930@opsconsole.internal>" },
          },
        ],
      },
      {
        id: "del-002-3",
        notificationId: "notif-002",
        channelType: "SLACK",
        destination: "#ops-alerts",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T09:30:01.500Z",
        createdAt: "2026-03-02T09:30:00.000Z",
        updatedAt: "2026-03-02T09:30:01.500Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T09:30:01.500Z",
            adapter: "SlackNotificationAdapter",
            channelType: "SLACK",
            destination: "#ops-alerts",
            metadata: { simulated: true, mode: "LOCAL_SIMULATED" },
          },
        ],
      },
    ],
  },
  {
    id: "notif-003",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    source: "ALERT",
    sourceId: "alert-003",
    serviceId: "srv-payment-gw",
    serviceName: "Payment Gateway",
    severity: "SEV3",
    eventType: "ALERT_FIRING",
    title: "Dependency Latency Warning on Payment Gateway",
    message: "Upstream third-party payment rail response latency elevated to 180ms.",
    status: "DELIVERED",
    fingerprint: "ws-demo:env-prod:ALERT:alert-003:ALERT_FIRING",
    ruleId: "rule-sev3-warning",
    ruleName: "SEV3 / Moderate Warning Routing",
    relatedAlertId: "alert-003",
    isSimulated: true,
    createdAt: "2026-03-02T08:00:00.000Z",
    updatedAt: "2026-03-02T08:00:00.400Z",
    deliveries: [
      {
        id: "del-003-1",
        notificationId: "notif-003",
        channelType: "IN_APP",
        destination: "OpsConsole Live Activity Feed",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T08:00:00.400Z",
        createdAt: "2026-03-02T08:00:00.000Z",
        updatedAt: "2026-03-02T08:00:00.400Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T08:00:00.400Z",
            adapter: "InAppNotificationAdapter",
            channelType: "IN_APP",
            destination: "OpsConsole Live Activity Feed",
            metadata: { simulated: true },
          },
        ],
      },
    ],
  },
  {
    id: "notif-004",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    source: "INCIDENT",
    sourceId: "inc-0001",
    serviceId: "srv-notif-worker",
    serviceName: "Notification Worker",
    severity: "SEV1",
    eventType: "INCIDENT_CREATED",
    title: "INC-0001 Declared: Notification Worker Outage",
    message: "Major incident INC-0001 created for Notification Worker by Thejas. War room convened.",
    status: "PARTIALLY_FAILED",
    fingerprint: "ws-demo:env-prod:INCIDENT:inc-0001:INCIDENT_CREATED",
    ruleId: "rule-sev1-critical",
    ruleName: "SEV1 Critical Outage Immediate Escalation",
    relatedIncidentId: "inc-0001",
    isSimulated: true,
    createdAt: "2026-03-02T10:18:00.000Z",
    updatedAt: "2026-03-02T10:18:03.000Z",
    deliveries: [
      {
        id: "del-004-1",
        notificationId: "notif-004",
        channelType: "IN_APP",
        destination: "OpsConsole Live Activity Feed",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T10:18:00.500Z",
        createdAt: "2026-03-02T10:18:00.000Z",
        updatedAt: "2026-03-02T10:18:00.500Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T10:18:00.500Z",
            adapter: "InAppNotificationAdapter",
            channelType: "IN_APP",
            destination: "OpsConsole Live Activity Feed",
            metadata: { simulated: true },
          },
        ],
      },
      {
        id: "del-004-2",
        notificationId: "notif-004",
        channelType: "SLACK",
        destination: "#sre-critical",
        status: "DELIVERED",
        attemptCount: 1,
        deliveredAt: "2026-03-02T10:18:01.000Z",
        createdAt: "2026-03-02T10:18:00.000Z",
        updatedAt: "2026-03-02T10:18:01.000Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "DELIVERED",
            timestamp: "2026-03-02T10:18:01.000Z",
            adapter: "SlackNotificationAdapter",
            channelType: "SLACK",
            destination: "#sre-critical",
            metadata: { simulated: true },
          },
        ],
      },
      {
        id: "del-004-3",
        notificationId: "notif-004",
        channelType: "WEBHOOK",
        destination: "https://fail.external.invalid/webhook",
        status: "FAILED",
        attemptCount: 2,
        failureReason: "Simulated Webhook delivery failed: HTTP 503 Service Unavailable / Connection timeout.",
        createdAt: "2026-03-02T10:18:00.000Z",
        updatedAt: "2026-03-02T10:18:03.000Z",
        attempts: [
          {
            attemptNumber: 1,
            status: "FAILED",
            timestamp: "2026-03-02T10:18:01.500Z",
            adapter: "WebhookNotificationAdapter",
            channelType: "WEBHOOK",
            destination: "https://fail.external.invalid/webhook",
            error: "Simulated Webhook delivery failed: HTTP 503 Service Unavailable / Connection timeout.",
            metadata: { simulated: true, httpStatus: 503 },
          },
          {
            attemptNumber: 2,
            status: "FAILED",
            timestamp: "2026-03-02T10:18:03.000Z",
            adapter: "WebhookNotificationAdapter",
            channelType: "WEBHOOK",
            destination: "https://fail.external.invalid/webhook",
            error: "Simulated Webhook delivery failed: HTTP 503 Service Unavailable / Connection timeout.",
            metadata: { simulated: true, httpStatus: 503 },
          },
        ],
      },
    ],
  },
  {
    id: "notif-005",
    workspaceId: DEFAULT_WORKSPACE_ID,
    environmentId: DEFAULT_ENVIRONMENT_ID,
    source: "ALERT",
    sourceId: "alert-001",
    serviceId: "srv-notif-worker",
    serviceName: "Notification Worker",
    severity: "SEV1",
    eventType: "ALERT_FIRING",
    title: "High Error Rate (> 2.0%) on Notification Worker",
    message: "Repeated trigger suppressed: active alert already notified within cooldown window.",
    status: "SUPPRESSED",
    fingerprint: "ws-demo:env-prod:ALERT:alert-001:ALERT_FIRING",
    ruleId: "rule-sev1-critical",
    ruleName: "SEV1 Critical Outage Immediate Escalation",
    relatedAlertId: "alert-001",
    suppressionReason: "Deduplicated: active alert already notified within cooldown window (4 mins remaining)",
    isSimulated: true,
    createdAt: "2026-03-02T10:16:00.000Z",
    updatedAt: "2026-03-02T10:16:00.000Z",
    deliveries: [],
  },
];

// ─── Seeded User Preferences ──────────────────────────────────────────────────

export const SEEDED_PREFERENCES: NotificationPreference[] = [
  {
    id: "pref-thejas",
    workspaceId: DEFAULT_WORKSPACE_ID,
    userId: "usr-thejas",
    isEnabled: true,
    channelPreferences: {
      IN_APP: true,
      SLACK: true,
      WEBHOOK: true,
      EMAIL: true,
      TEAMS: true,
    },
    severityPreferences: {
      SEV1: true,
      SEV2: true,
      SEV3: true,
      SEV4: true,
      INFO: true,
    },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "pref-alex",
    workspaceId: DEFAULT_WORKSPACE_ID,
    userId: "usr-alex",
    isEnabled: true,
    channelPreferences: {
      IN_APP: true,
      SLACK: true,
      WEBHOOK: false,
      EMAIL: true,
      TEAMS: false,
    },
    severityPreferences: {
      SEV1: true,
      SEV2: true,
      SEV3: true,
      SEV4: false,
      INFO: false,
    },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "pref-priya",
    workspaceId: DEFAULT_WORKSPACE_ID,
    userId: "usr-priya",
    isEnabled: true,
    channelPreferences: {
      IN_APP: true,
      SLACK: false,
      WEBHOOK: false,
      EMAIL: true,
      TEAMS: false,
    },
    severityPreferences: {
      SEV1: true,
      SEV2: true,
      SEV3: false,
      SEV4: false,
      INFO: false,
    },
    createdAt: "2026-03-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

// ─── Local Store Class ────────────────────────────────────────────────────────

export class LocalNotificationStore {
  public notifications: Notification[] = [];
  public rules: NotificationRule[] = [];
  public channels: NotificationChannel[] = [];
  public preferences: NotificationPreference[] = [];

  constructor() {
    this.reset();
  }

  public reset(): void {
    this.notifications = JSON.parse(JSON.stringify(SEEDED_NOTIFICATIONS));
    this.rules = JSON.parse(JSON.stringify(SEEDED_RULES));
    this.channels = JSON.parse(JSON.stringify(SEEDED_CHANNELS));
    this.preferences = JSON.parse(JSON.stringify(SEEDED_PREFERENCES));
  }
}
