import type { ExternalWorkItem } from "./types";
import { createRealProvider, type ProviderKind, type Scope } from "./real-integrations";
import { SimulationAsanaProvider, SimulationJiraProvider } from "./integrations";

export type Proposal = { id: string; scope: Scope; provider: ProviderKind; projectId: string; incidentId?: string; payload: { title: string; description: string; providerProjectId?: string; workspaceId?: string; issueTypeId?: string; priorityId?: string; dueDate?: string; assigneeId?: string }; state: "PENDING" | "APPROVED" | "EXECUTED"; createdAt: string; approvedAt?: string; external?: ExternalWorkItem };
export type AuditEntry = { timestamp: string; userId: string; workspaceId: string; environmentId: string; provider: ProviderKind; operation: string; projectId: string; incidentId?: string; proposalId: string; result: "SUCCESS" | "FAILED"; externalId?: string; externalUrl?: string; errorCode?: string };
const proposals = new Map<string, Proposal>(); const audit: AuditEntry[] = [];
function id() { return `proposal-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`; }
export function providerMode() { return process.env.INTEGRATION_MODE === "real" ? "real" : "simulated"; }
export function createProposal(scope: Scope, provider: ProviderKind, projectId: string, incidentId: string | undefined, payload: Proposal["payload"]) { const proposal: Proposal = { id: id(), scope, provider, projectId, incidentId, payload, state: "PENDING", createdAt: new Date().toISOString() }; proposals.set(proposal.id, proposal); return proposal; }
export function approveProposal(scope: Scope, proposalId: string) { const proposal = proposals.get(proposalId); if (!proposal || proposal.scope.userId !== scope.userId || proposal.scope.workspaceId !== scope.workspaceId || proposal.scope.environmentId !== scope.environmentId) return null; if (proposal.state !== "PENDING") throw new Error("This proposal has already been approved or executed."); proposal.state = "APPROVED"; proposal.approvedAt = new Date().toISOString(); return proposal; }
export async function executeProposal(scope: Scope, proposalId: string) { const proposal = proposals.get(proposalId); if (!proposal || proposal.scope.userId !== scope.userId || proposal.scope.workspaceId !== scope.workspaceId || proposal.scope.environmentId !== scope.environmentId) return null; if (proposal.state !== "APPROVED") throw new Error("A recorded server-side approval is required before external work can be created."); try { const client = providerMode() === "real" ? createRealProvider(proposal.provider, scope) : proposal.provider === "JIRA" ? new SimulationJiraProvider() : new SimulationAsanaProvider(); const external = await client.createWorkItem({ ...proposal.payload, projectId: proposal.projectId, incidentId: proposal.incidentId, environment: scope.environmentId }); proposal.state = "EXECUTED"; proposal.external = external; audit.push({ timestamp: new Date().toISOString(), ...scope, provider: proposal.provider, operation: "CREATE", projectId: proposal.projectId, incidentId: proposal.incidentId, proposalId, result: "SUCCESS", externalId: external.externalId, externalUrl: external.url }); return proposal; } catch (error) { audit.push({ timestamp: new Date().toISOString(), ...scope, provider: proposal.provider, operation: "CREATE", projectId: proposal.projectId, incidentId: proposal.incidentId, proposalId, result: "FAILED", errorCode: error instanceof Error && "code" in error ? String((error as { code: string }).code) : "PROVIDER_ERROR" }); throw error; } }
export function recentExternalWork(scope: Scope) { return [...proposals.values()].filter(p => p.scope.workspaceId === scope.workspaceId && p.scope.environmentId === scope.environmentId && p.external).map(p => p.external!).slice(-20).reverse(); }
export function auditEntries() { return [...audit]; }
