"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, Loader2, Pencil, Plus, X } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { useIdentity } from "@/components/identity/IdentityProvider";
import type { Milestone, Project } from "@/modules/projects";
import { formatProjectDate, loadProjectPortfolio } from "@/app/projects/project-data";

export default function ProjectMilestonesPage() {
  const { workspace, activeEnvironment, can } = useIdentity();
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editor, setEditor] = useState<Milestone | null | undefined>(undefined);
  const canManage = can("projects:manage");
  const refresh = useCallback(() => workspace && activeEnvironment ? loadProjectPortfolio(workspace.id, activeEnvironment.id).then((data) => setProjects(data.projects)) : Promise.resolve(), [workspace, activeEnvironment]);

  useEffect(() => { refresh().catch((err: unknown) => setError(err instanceof Error ? err.message : "Unable to load milestones")).finally(() => setLoading(false)); }, [workspace, activeEnvironment]);
  const milestones = useMemo(() => projects.flatMap((project) => project.milestones.map((milestone) => ({ ...milestone, projectName: project.name, workItems: project.workItems.filter((item) => item.milestoneId === milestone.id), risks: project.risks.filter((risk) => risk.projectId === project.id), links: project.linkedOperationalEntities }))), [projects]);

  async function saveMilestone(input: Record<string, string>) {
    if (!workspace || !activeEnvironment) return;
    const existing = editor && editor !== null ? editor : null;
    const response = await fetch("/api/projects/milestones", { method: existing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ workspaceId: workspace.id, environmentId: activeEnvironment.id, ...(existing ? { milestoneId: existing.id } : {}), ...input }) });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || "Unable to save milestone");
    setEditor(undefined);
    await refresh();
  }

  if (!can("projects:read")) return <PermissionNotice />;
  return <div className="space-y-6"><PageHeader icon={CalendarDays} title="Project Milestones" subtitle="Delivery checkpoints, operational context, and schedule health." iconColor="#f59e0b" iconBgColor="rgba(245, 158, 11, 0.12)" actions={canManage ? <button type="button" onClick={() => setEditor(null)} className="inline-flex items-center gap-2 rounded-lg bg-amber-500/15 px-3 py-2 text-xs font-semibold text-amber-200 border border-amber-500/30"><Plus size={14} /> New Milestone</button> : undefined} />{loading && <LoadingState />}{error && <ErrorState message={error} />}{!loading && !error && <><ScopeBanner workspaceName={workspace?.name} environmentName={activeEnvironment?.name} />{editor !== undefined && <MilestoneEditor milestone={editor} projects={projects} onCancel={() => setEditor(undefined)} onSave={saveMilestone} />}<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{milestones.map((milestone) => <div key={milestone.id} className={`rounded-2xl surface-card p-5 border ${milestone.status === "DELAYED" ? "border-rose-500/30" : "border-white/[0.06]"}`}><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider text-slate-400">{milestone.projectName}</div><h2 className="mt-2 text-lg font-semibold text-white">{milestone.name}</h2></div><span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-[10px] font-semibold text-amber-200">{milestone.status}</span></div><p className="mt-2 text-sm text-slate-300">{milestone.description}</p><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><Info label="Owner" value={milestone.owner} /><Info label="Planned" value={formatProjectDate(milestone.plannedDate)} /><Info label="Actual" value={formatProjectDate(milestone.actualDate)} /><Info label="Related work" value={String(milestone.workItems.length)} /></div>{milestone.status === "DELAYED" && <div className="mt-4 flex gap-2 text-xs text-rose-200"><AlertTriangle size={14} /> Delayed milestone requires delivery review.</div>}<div className="mt-4 flex items-center justify-between border-t border-white/[0.06] pt-3 text-[11px] text-slate-400"><span>{milestone.risks.length} project risks · {milestone.links.length} operational links</span>{canManage && <button type="button" onClick={() => setEditor(milestone)} className="text-slate-400 hover:text-amber-200"><Pencil size={13} /></button>}</div></div>)}</div>{milestones.length === 0 && <EmptyState />}</>}</div>;
}

function MilestoneEditor({ milestone, projects, onCancel, onSave }: { milestone: Milestone | null; projects: Project[]; onCancel: () => void; onSave: (input: Record<string, string>) => Promise<void> }) { const [form, setForm] = useState({ projectId: milestone?.projectId || projects[0]?.id || "", name: milestone?.name || "", description: milestone?.description || "", owner: milestone?.owner || "", plannedDate: milestone?.plannedDate?.slice(0, 10) || "", actualDate: milestone?.actualDate?.slice(0, 10) || "", status: milestone?.status || "PLANNED" }); const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value })); return <form onSubmit={(event) => { event.preventDefault(); void onSave(form); }} className="rounded-2xl border border-amber-500/30 bg-amber-500/5 p-5 mb-4 space-y-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-white">{milestone ? "Edit milestone" : "New milestone"}</h2><button type="button" onClick={onCancel}><X size={16} className="text-slate-400" /></button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><MilestoneField label="Project" value={form.projectId} options={projects.map((project) => project.id)} onChange={(value) => update("projectId", value)} /><MilestoneField label="Name" value={form.name} onChange={(value) => update("name", value)} /><MilestoneField label="Owner" value={form.owner} onChange={(value) => update("owner", value)} /><MilestoneField label="Planned date" type="date" value={form.plannedDate} onChange={(value) => update("plannedDate", value)} /><MilestoneField label="Actual date" type="date" value={form.actualDate} onChange={(value) => update("actualDate", value)} /><MilestoneField label="Status" value={form.status} options={["PLANNED", "IN_PROGRESS", "COMPLETED", "DELAYED"]} onChange={(value) => update("status", value)} /></div><label className="block text-[11px] uppercase tracking-wider text-slate-400">Description<textarea value={form.description} onChange={(event) => update("description", event.target.value)} className="mt-1 min-h-16 w-full rounded-lg border border-white/[0.08] bg-[#0c1322] px-3 py-2 text-xs text-slate-200" /></label><div className="flex justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-lg border border-white/[0.08] px-3 py-2 text-xs text-slate-300">Cancel</button><button type="submit" className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-slate-950">Save milestone</button></div></form>; }
function MilestoneField({ label, value, onChange, options, type = "text" }: { label: string; value: string; onChange: (value: string) => void; options?: string[]; type?: string }) { return <label className="text-[11px] uppercase tracking-wider text-slate-400">{label}{options ? <select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border border-white/[0.08] bg-[#0c1322] px-3 py-2 text-xs text-slate-200">{options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={label !== "Actual date"} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-lg border border-white/[0.08] bg-[#0c1322] px-3 py-2 text-xs text-slate-200" />}</label>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-white/[0.03] p-3"><div className="text-slate-500">{label}</div><div className="mt-1 font-semibold text-slate-200">{value}</div></div>; }
function ScopeBanner({ workspaceName, environmentName }: { workspaceName?: string; environmentName?: string }) { return <div className="rounded-xl border border-cyan-500/20 bg-cyan-500/5 px-4 py-3 text-xs text-cyan-100">Active scope: <span className="font-semibold">{workspaceName || "Workspace"}</span> / <span className="font-semibold">{environmentName || "Environment"}</span> · SIMULATED</div>; }
function LoadingState() { return <div className="rounded-2xl surface-card p-12 flex justify-center gap-3 text-sm text-slate-400"><Loader2 size={18} className="animate-spin text-amber-400" /> Loading milestones...</div>; }
function ErrorState({ message }: { message: string }) { return <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300 flex gap-2"><AlertTriangle size={16} />{message}</div>; }
function EmptyState() { return <div className="rounded-2xl surface-card p-10 text-center text-sm text-slate-400">No milestones found in the active scope.</div>; }
function PermissionNotice() { return <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-5 text-sm text-rose-300">You do not have permission to view project milestones.</div>; }
